# Site settings
description: Blog onde escrevo sobre python, agile, coisas que estudo e um pouco das minhas experiências
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://giovaneliberato.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Giovane Liberato
user_description: python developer and security enthusiast
user_title: ""
email: giovaneliberato@gmail.com
twitter_username: giovaneliberato
github_username:  giovaneliberato

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
